// ── Scenario definitions ───────────────────────────────────────────────────────
//
// Single source of truth for every scenario the app can display.
// Fields:
//   id          – unique identifier matching the processed JSON filename
//   label       – human-readable button text
//   group       – position group for grouping buttons (BB, SB, BTN, CO, HJ, UTG)
//   section     – section name shown in the type filter
//   hidden      – true = not shown in selector (activated by a toggle)
//   coldCaller  – true = this scenario has an RFI-folds toggle
//   callLabel   – override the "Call" label (e.g. 'Limp' for SB RFI)
// ─────────────────────────────────────────────────────────────────────────────

const SCENARIO_DEFS = [
  // ── RFI ────────────────────────────────────────────────────
  { id: 'rfi_utg', label: 'UTG', group: 'RFI', section: 'RFI' },
  { id: 'rfi_hj',  label: 'HJ',  group: 'RFI', section: 'RFI' },
  { id: 'rfi_co',  label: 'CO',  group: 'RFI', section: 'RFI' },
  { id: 'rfi_btn', label: 'BTN', group: 'RFI', section: 'RFI' },
  { id: 'rfi_sb',  label: 'SB',  group: 'RFI', section: 'RFI', callLabel: 'Limp' },
  // ── vs RFI ─────────────────────────────────────────────────
  { id: 'bb_vs_utg',  label: 'vs UTG', group: 'BB',  section: 'vs RFI' },
  { id: 'bb_vs_hj',   label: 'vs HJ',  group: 'BB',  section: 'vs RFI' },
  { id: 'bb_vs_co',   label: 'vs CO',  group: 'BB',  section: 'vs RFI' },
  { id: 'bb_vs_btn',  label: 'vs BTN', group: 'BB',  section: 'vs RFI' },
  { id: 'bb_vs_sb',   label: 'vs SB',  group: 'BB',  section: 'vs RFI' },
  { id: 'sb_vs_utg',  label: 'vs UTG', group: 'SB',  section: 'vs RFI' },
  { id: 'sb_vs_hj',   label: 'vs HJ',  group: 'SB',  section: 'vs RFI' },
  { id: 'sb_vs_co',   label: 'vs CO',  group: 'SB',  section: 'vs RFI' },
  { id: 'sb_vs_btn',  label: 'vs BTN', group: 'SB',  section: 'vs RFI' },
  { id: 'sb_vs_bb',   label: 'vs BB',  group: 'SB',  section: 'vs RFI' },
  { id: 'btn_vs_utg', label: 'vs UTG', group: 'BTN', section: 'vs RFI' },
  { id: 'btn_vs_hj',  label: 'vs HJ',  group: 'BTN', section: 'vs RFI' },
  { id: 'btn_vs_co',  label: 'vs CO',  group: 'BTN', section: 'vs RFI' },
  { id: 'co_vs_utg',  label: 'vs UTG', group: 'CO',  section: 'vs RFI' },
  { id: 'co_vs_hj',   label: 'vs HJ',  group: 'CO',  section: 'vs RFI' },
  { id: 'hj_vs_utg',  label: 'vs UTG', group: 'HJ',  section: 'vs RFI' },
  // ── vs 3-bet ───────────────────────────────────────────────
  { id: 'utg_vs_3b_hj',  label: 'vs HJ 3b',  group: 'UTG', section: 'vs 3b' },
  { id: 'utg_vs_3b_co',  label: 'vs CO 3b',  group: 'UTG', section: 'vs 3b' },
  { id: 'utg_vs_3b_btn', label: 'vs BTN 3b', group: 'UTG', section: 'vs 3b' },
  { id: 'utg_vs_3b_sb',  label: 'vs SB 3b',  group: 'UTG', section: 'vs 3b' },
  { id: 'utg_vs_3b_bb',  label: 'vs BB 3b',  group: 'UTG', section: 'vs 3b' },
  { id: 'hj_vs_3b_co',   label: 'vs CO 3b',  group: 'HJ',  section: 'vs 3b' },
  { id: 'hj_vs_3b_btn',  label: 'vs BTN 3b', group: 'HJ',  section: 'vs 3b' },
  { id: 'hj_vs_3b_sb',   label: 'vs SB 3b',  group: 'HJ',  section: 'vs 3b' },
  { id: 'hj_vs_3b_bb',   label: 'vs BB 3b',  group: 'HJ',  section: 'vs 3b' },
  { id: 'co_vs_3b_btn',  label: 'vs BTN 3b', group: 'CO',  section: 'vs 3b' },
  { id: 'co_vs_3b_sb',   label: 'vs SB 3b',  group: 'CO',  section: 'vs 3b' },
  { id: 'co_vs_3b_bb',   label: 'vs BB 3b',  group: 'CO',  section: 'vs 3b' },
  { id: 'btn_vs_3b_sb',  label: 'vs SB 3b',  group: 'BTN', section: 'vs 3b' },
  { id: 'btn_vs_3b_bb',  label: 'vs BB 3b',  group: 'BTN', section: 'vs 3b' },
  { id: 'sb_vs_3b_bb',   label: 'vs BB 3b',  group: 'SB',  section: 'vs 3b' },
  { id: 'bb_vs_3b_sb',   label: 'vs SB 3b',  group: 'BB',  section: 'vs 3b' },
  // ── vs 4-bet ───────────────────────────────────────────────
  { id: 'bb_vs_4b_utg',  label: 'vs UTG 4b', group: 'BB',  section: 'vs 4b' },
  { id: 'bb_vs_4b_hj',   label: 'vs HJ 4b',  group: 'BB',  section: 'vs 4b' },
  { id: 'bb_vs_4b_co',   label: 'vs CO 4b',  group: 'BB',  section: 'vs 4b' },
  { id: 'bb_vs_4b_btn',  label: 'vs BTN 4b', group: 'BB',  section: 'vs 4b' },
  { id: 'bb_vs_4b_sb',   label: 'vs SB 4b',  group: 'BB',  section: 'vs 4b' },
  { id: 'sb_vs_4b_bb',   label: 'vs BB 4b',  group: 'SB',  section: 'vs 4b' },
  { id: 'sb_vs_4b_utg',  label: 'vs UTG 4b', group: 'SB',  section: 'vs 4b' },
  { id: 'sb_vs_4b_hj',   label: 'vs HJ 4b',  group: 'SB',  section: 'vs 4b' },
  { id: 'sb_vs_4b_co',   label: 'vs CO 4b',  group: 'SB',  section: 'vs 4b' },
  { id: 'sb_vs_4b_btn',  label: 'vs BTN 4b', group: 'SB',  section: 'vs 4b' },
  { id: 'btn_vs_4b_utg', label: 'vs UTG 4b', group: 'BTN', section: 'vs 4b' },
  { id: 'btn_vs_4b_hj',  label: 'vs HJ 4b',  group: 'BTN', section: 'vs 4b' },
  { id: 'btn_vs_4b_co',  label: 'vs CO 4b',  group: 'BTN', section: 'vs 4b' },
  { id: 'co_vs_4b_utg',  label: 'vs UTG 4b', group: 'CO',  section: 'vs 4b' },
  { id: 'co_vs_4b_hj',   label: 'vs HJ 4b',  group: 'CO',  section: 'vs 4b' },
  { id: 'hj_vs_4b_utg',  label: 'vs UTG 4b', group: 'HJ',  section: 'vs 4b' },
  // ── vs 4-bet all-in (hidden — activated via toggle in vs 4b section) ──
  { id: 'bb_vs_4b_allin_utg',  label: 'vs UTG 4b', group: 'BB',  section: 'vs 4b allin', hidden: true },
  { id: 'bb_vs_4b_allin_hj',   label: 'vs HJ 4b',  group: 'BB',  section: 'vs 4b allin', hidden: true },
  { id: 'bb_vs_4b_allin_co',   label: 'vs CO 4b',  group: 'BB',  section: 'vs 4b allin', hidden: true },
  { id: 'bb_vs_4b_allin_btn',  label: 'vs BTN 4b', group: 'BB',  section: 'vs 4b allin', hidden: true },
  { id: 'bb_vs_4b_allin_sb',   label: 'vs SB 4b',  group: 'BB',  section: 'vs 4b allin', hidden: true },
  { id: 'sb_vs_4b_allin_utg',  label: 'vs UTG 4b', group: 'SB',  section: 'vs 4b allin', hidden: true },
  { id: 'sb_vs_4b_allin_hj',   label: 'vs HJ 4b',  group: 'SB',  section: 'vs 4b allin', hidden: true },
  { id: 'sb_vs_4b_allin_co',   label: 'vs CO 4b',  group: 'SB',  section: 'vs 4b allin', hidden: true },
  { id: 'sb_vs_4b_allin_btn',  label: 'vs BTN 4b', group: 'SB',  section: 'vs 4b allin', hidden: true },
  { id: 'btn_vs_4b_allin_utg', label: 'vs UTG 4b', group: 'BTN', section: 'vs 4b allin', hidden: true },
  { id: 'btn_vs_4b_allin_hj',  label: 'vs HJ 4b',  group: 'BTN', section: 'vs 4b allin', hidden: true },
  { id: 'btn_vs_4b_allin_co',  label: 'vs CO 4b',  group: 'BTN', section: 'vs 4b allin', hidden: true },
  { id: 'co_vs_4b_allin_utg',  label: 'vs UTG 4b', group: 'CO',  section: 'vs 4b allin', hidden: true },
  { id: 'co_vs_4b_allin_hj',   label: 'vs HJ 4b',  group: 'CO',  section: 'vs 4b allin', hidden: true },
  { id: 'hj_vs_4b_allin_utg',  label: 'vs UTG 4b', group: 'HJ',  section: 'vs 4b allin', hidden: true },
  // ── vs 5-bet ───────────────────────────────────────────────
  { id: 'utg_vs_5b_bb',  label: 'vs BB 5b',  group: 'UTG', section: 'vs 5b' },
  { id: 'utg_vs_5b_sb',  label: 'vs SB 5b',  group: 'UTG', section: 'vs 5b' },
  { id: 'utg_vs_5b_btn', label: 'vs BTN 5b', group: 'UTG', section: 'vs 5b' },
  { id: 'utg_vs_5b_co',  label: 'vs CO 5b',  group: 'UTG', section: 'vs 5b' },
  { id: 'utg_vs_5b_hj',  label: 'vs HJ 5b',  group: 'UTG', section: 'vs 5b' },
  { id: 'hj_vs_5b_bb',   label: 'vs BB 5b',  group: 'HJ',  section: 'vs 5b' },
  { id: 'hj_vs_5b_sb',   label: 'vs SB 5b',  group: 'HJ',  section: 'vs 5b' },
  { id: 'hj_vs_5b_btn',  label: 'vs BTN 5b', group: 'HJ',  section: 'vs 5b' },
  { id: 'hj_vs_5b_co',   label: 'vs CO 5b',  group: 'HJ',  section: 'vs 5b' },
  { id: 'co_vs_5b_bb',   label: 'vs BB 5b',  group: 'CO',  section: 'vs 5b' },
  { id: 'co_vs_5b_sb',   label: 'vs SB 5b',  group: 'CO',  section: 'vs 5b' },
  { id: 'co_vs_5b_btn',  label: 'vs BTN 5b', group: 'CO',  section: 'vs 5b' },
  { id: 'btn_vs_5b_bb',  label: 'vs BB 5b',  group: 'BTN', section: 'vs 5b' },
  { id: 'btn_vs_5b_sb',  label: 'vs SB 5b',  group: 'BTN', section: 'vs 5b' },
  { id: 'sb_vs_5b_bb',   label: 'vs BB 5b',  group: 'SB',  section: 'vs 5b' },
  // ── sqz (cold call + squeeze) ─────────────────────────────────────────────
  { id: 'co_vs_utg_hj',  label: 'UTG+HJ',  group: 'CO',  section: 'sqz' },
  { id: 'btn_vs_utg_hj', label: 'UTG+HJ',  group: 'BTN', section: 'sqz' },
  { id: 'btn_vs_utg_co', label: 'UTG+CO',  group: 'BTN', section: 'sqz' },
  { id: 'btn_vs_hj_co',  label: 'HJ+CO',   group: 'BTN', section: 'sqz' },
  { id: 'sb_vs_utg_hj',  label: 'UTG+HJ',  group: 'SB',  section: 'sqz' },
  { id: 'sb_vs_utg_co',  label: 'UTG+CO',  group: 'SB',  section: 'sqz' },
  { id: 'sb_vs_utg_btn', label: 'UTG+BTN', group: 'SB',  section: 'sqz' },
  { id: 'sb_vs_hj_co',   label: 'HJ+CO',   group: 'SB',  section: 'sqz' },
  { id: 'sb_vs_hj_btn',  label: 'HJ+BTN',  group: 'SB',  section: 'sqz' },
  { id: 'sb_vs_co_btn',  label: 'CO+BTN',  group: 'SB',  section: 'sqz' },
  { id: 'bb_vs_utg_hj',  label: 'UTG+HJ',  group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_utg_co',  label: 'UTG+CO',  group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_utg_btn', label: 'UTG+BTN', group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_utg_sb',  label: 'UTG+SB',  group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_hj_co',   label: 'HJ+CO',   group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_hj_btn',  label: 'HJ+BTN',  group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_hj_sb',   label: 'HJ+SB',   group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_co_btn',  label: 'CO+BTN',  group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_co_sb',   label: 'CO+SB',   group: 'BB',  section: 'sqz' },
  { id: 'bb_vs_btn_sb',  label: 'BTN+SB',  group: 'BB',  section: 'sqz' },
  // ── vs sqz ────────────────────────────────────────────────────────────
  { id: 'utg_vs_sqz_hj_co',   label: 'HJ+CO',   group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_hj_btn',  label: 'HJ+BTN',  group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_hj_sb',   label: 'HJ+SB',   group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_hj_bb',   label: 'HJ+BB',   group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_co_btn',  label: 'CO+BTN',  group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_co_sb',   label: 'CO+SB',   group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_co_bb',   label: 'CO+BB',   group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_btn_sb',  label: 'BTN+SB',  group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_btn_bb',  label: 'BTN+BB',  group: 'UTG', section: 'vs sqz' },
  { id: 'utg_vs_sqz_sb_bb',   label: 'SB+BB',   group: 'UTG', section: 'vs sqz' },
  { id: 'hj_vs_sqz_co_btn',   label: 'CO+BTN',  group: 'HJ',  section: 'vs sqz' },
  { id: 'hj_vs_sqz_co_sb',    label: 'CO+SB',   group: 'HJ',  section: 'vs sqz' },
  { id: 'hj_vs_sqz_co_bb',    label: 'CO+BB',   group: 'HJ',  section: 'vs sqz' },
  { id: 'hj_vs_sqz_btn_sb',   label: 'BTN+SB',  group: 'HJ',  section: 'vs sqz' },
  { id: 'hj_vs_sqz_btn_bb',   label: 'BTN+BB',  group: 'HJ',  section: 'vs sqz' },
  { id: 'hj_vs_sqz_sb_bb',    label: 'SB+BB',   group: 'HJ',  section: 'vs sqz' },
  { id: 'co_vs_sqz_btn_sb',   label: 'BTN+SB',  group: 'CO',  section: 'vs sqz' },
  { id: 'co_vs_sqz_btn_bb',   label: 'BTN+BB',  group: 'CO',  section: 'vs sqz' },
  { id: 'co_vs_sqz_sb_bb',    label: 'SB+BB',   group: 'CO',  section: 'vs sqz' },
  { id: 'btn_vs_sqz_sb_bb',   label: 'SB+BB',   group: 'BTN', section: 'vs sqz' },
  { id: 'hj_vs_sqz_utg_co',   label: 'UTG+CO',  group: 'HJ',  section: 'vs sqz', coldCaller: true },
  { id: 'hj_vs_sqz_utg_btn',  label: 'UTG+BTN', group: 'HJ',  section: 'vs sqz', coldCaller: true },
  { id: 'hj_vs_sqz_utg_sb',   label: 'UTG+SB',  group: 'HJ',  section: 'vs sqz', coldCaller: true },
  { id: 'hj_vs_sqz_utg_bb',   label: 'UTG+BB',  group: 'HJ',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_utg_btn',  label: 'UTG+BTN', group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_utg_sb',   label: 'UTG+SB',  group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_utg_bb',   label: 'UTG+BB',  group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_hj_btn',   label: 'HJ+BTN',  group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_hj_sb',    label: 'HJ+SB',   group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'co_vs_sqz_hj_bb',    label: 'HJ+BB',   group: 'CO',  section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_utg_sb',  label: 'UTG+SB',  group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_utg_bb',  label: 'UTG+BB',  group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_hj_sb',   label: 'HJ+SB',   group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_hj_bb',   label: 'HJ+BB',   group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_co_sb',   label: 'CO+SB',   group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'btn_vs_sqz_co_bb',   label: 'CO+BB',   group: 'BTN', section: 'vs sqz', coldCaller: true },
  { id: 'sb_vs_sqz_utg_bb',   label: 'UTG+BB',  group: 'SB',  section: 'vs sqz', coldCaller: true },
  { id: 'sb_vs_sqz_hj_bb',    label: 'HJ+BB',   group: 'SB',  section: 'vs sqz', coldCaller: true },
  { id: 'sb_vs_sqz_co_bb',    label: 'CO+BB',   group: 'SB',  section: 'vs sqz', coldCaller: true },
  { id: 'sb_vs_sqz_btn_bb',   label: 'BTN+BB',  group: 'SB',  section: 'vs sqz', coldCaller: true },
  // ── vs sqz cold caller (RFI fold) — hidden, activated via toggle ──────────
  { id: 'hj_vs_sqz_utg_co_rfi_fold',  label: 'UTG+CO',  group: 'HJ',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'hj_vs_sqz_utg_btn_rfi_fold', label: 'UTG+BTN', group: 'HJ',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'hj_vs_sqz_utg_sb_rfi_fold',  label: 'UTG+SB',  group: 'HJ',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'hj_vs_sqz_utg_bb_rfi_fold',  label: 'UTG+BB',  group: 'HJ',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_utg_btn_rfi_fold', label: 'UTG+BTN', group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_utg_sb_rfi_fold',  label: 'UTG+SB',  group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_utg_bb_rfi_fold',  label: 'UTG+BB',  group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_hj_btn_rfi_fold',  label: 'HJ+BTN',  group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_hj_sb_rfi_fold',   label: 'HJ+SB',   group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'co_vs_sqz_hj_bb_rfi_fold',   label: 'HJ+BB',   group: 'CO',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_utg_sb_rfi_fold', label: 'UTG+SB',  group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_utg_bb_rfi_fold', label: 'UTG+BB',  group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_hj_sb_rfi_fold',  label: 'HJ+SB',   group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_hj_bb_rfi_fold',  label: 'HJ+BB',   group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_co_sb_rfi_fold',  label: 'CO+SB',   group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'btn_vs_sqz_co_bb_rfi_fold',  label: 'CO+BB',   group: 'BTN', section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'sb_vs_sqz_utg_bb_rfi_fold',  label: 'UTG+BB',  group: 'SB',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'sb_vs_sqz_hj_bb_rfi_fold',   label: 'HJ+BB',   group: 'SB',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'sb_vs_sqz_co_bb_rfi_fold',   label: 'CO+BB',   group: 'SB',  section: 'vs sqz', coldCaller: true, hidden: true },
  { id: 'sb_vs_sqz_btn_bb_rfi_fold',  label: 'BTN+BB',  group: 'SB',  section: 'vs sqz', coldCaller: true, hidden: true },
  // ── sqz vs 4b (squeezer faces 4-bet)
  // ID scheme: {sqz}_sqz_vs_{opener}_4b_{cc}_fold  (opener 4-bets, CC folds)
  //            {sqz}_sqz_vs_{opener}_fold_{cc}_4b   (opener folds, CC 4-bets)
  //            {sqz}_sqz_vs_{opener}_call_{cc}_4b   (opener calls, CC 4-bets)
  { id: 'co_sqz_vs_utg_4b_hj_fold',   label: 'UTG 4b+HJ fold',  group: 'CO',  section: 'sqz vs 4b' },
  { id: 'co_sqz_vs_utg_fold_hj_4b',   label: 'UTG fold+HJ 4b',  group: 'CO',  section: 'sqz vs 4b' },
  { id: 'co_sqz_vs_utg_call_hj_4b',   label: 'UTG call+HJ 4b',  group: 'CO',  section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_4b_hj_fold',  label: 'UTG 4b+HJ fold',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_fold_hj_4b',  label: 'UTG fold+HJ 4b',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_call_hj_4b',  label: 'UTG call+HJ 4b',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_4b_co_fold',  label: 'UTG 4b+CO fold',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_fold_co_4b',  label: 'UTG fold+CO 4b',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_utg_call_co_4b',  label: 'UTG call+CO 4b',  group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_hj_4b_co_fold',   label: 'HJ 4b+CO fold',   group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_hj_fold_co_4b',   label: 'HJ fold+CO 4b',   group: 'BTN', section: 'sqz vs 4b' },
  { id: 'btn_sqz_vs_hj_call_co_4b',   label: 'HJ call+CO 4b',   group: 'BTN', section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_4b_hj_fold',   label: 'UTG 4b+HJ fold',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_fold_hj_4b',   label: 'UTG fold+HJ 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_call_hj_4b',   label: 'UTG call+HJ 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_4b_co_fold',   label: 'UTG 4b+CO fold',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_fold_co_4b',   label: 'UTG fold+CO 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_call_co_4b',   label: 'UTG call+CO 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_4b_btn_fold',  label: 'UTG 4b+BTN fold', group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_fold_btn_4b',  label: 'UTG fold+BTN 4b', group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_utg_call_btn_4b',  label: 'UTG call+BTN 4b', group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_4b_co_fold',    label: 'HJ 4b+CO fold',   group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_fold_co_4b',    label: 'HJ fold+CO 4b',   group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_call_co_4b',    label: 'HJ call+CO 4b',   group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_4b_btn_fold',   label: 'HJ 4b+BTN fold',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_fold_btn_4b',   label: 'HJ fold+BTN 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_hj_call_btn_4b',   label: 'HJ call+BTN 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_co_4b_btn_fold',   label: 'CO 4b+BTN fold',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_co_fold_btn_4b',   label: 'CO fold+BTN 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'sb_sqz_vs_co_call_btn_4b',   label: 'CO call+BTN 4b',  group: 'SB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_4b_hj_fold',   label: 'UTG 4b+HJ fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_fold_hj_4b',   label: 'UTG fold+HJ 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_call_hj_4b',   label: 'UTG call+HJ 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_4b_co_fold',   label: 'UTG 4b+CO fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_fold_co_4b',   label: 'UTG fold+CO 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_call_co_4b',   label: 'UTG call+CO 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_4b_btn_fold',  label: 'UTG 4b+BTN fold', group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_fold_btn_4b',  label: 'UTG fold+BTN 4b', group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_call_btn_4b',  label: 'UTG call+BTN 4b', group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_4b_sb_fold',   label: 'UTG 4b+SB fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_fold_sb_4b',   label: 'UTG fold+SB 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_utg_call_sb_4b',   label: 'UTG call+SB 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_4b_co_fold',    label: 'HJ 4b+CO fold',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_fold_co_4b',    label: 'HJ fold+CO 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_call_co_4b',    label: 'HJ call+CO 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_4b_btn_fold',   label: 'HJ 4b+BTN fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_fold_btn_4b',   label: 'HJ fold+BTN 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_call_btn_4b',   label: 'HJ call+BTN 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_4b_sb_fold',    label: 'HJ 4b+SB fold',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_fold_sb_4b',    label: 'HJ fold+SB 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_hj_call_sb_4b',    label: 'HJ call+SB 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_4b_btn_fold',   label: 'CO 4b+BTN fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_fold_btn_4b',   label: 'CO fold+BTN 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_call_btn_4b',   label: 'CO call+BTN 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_4b_sb_fold',    label: 'CO 4b+SB fold',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_fold_sb_4b',    label: 'CO fold+SB 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_co_call_sb_4b',    label: 'CO call+SB 4b',   group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_btn_4b_sb_fold',   label: 'BTN 4b+SB fold',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_btn_fold_sb_4b',   label: 'BTN fold+SB 4b',  group: 'BB',  section: 'sqz vs 4b' },
  { id: 'bb_sqz_vs_btn_call_sb_4b',   label: 'BTN call+SB 4b',  group: 'BB',  section: 'sqz vs 4b' },
  // ── vs limpers ─────────────────────────────────────────────
  { id: 'bb_vs_limp_sb', label: 'vs SB limp', group: 'BB', section: 'vs limp' },
]

export default SCENARIO_DEFS
